# https://circleci.com/docs/2.0

version: 2
jobs:

  infrastructure:
        docker:
          - image: alpine:3.8
        working_directory: ~/sampleform/
        steps:
          - checkout
              path: ~/sampleform
          - run:
              name: Install Terraform
              command: |
                wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
                unzip terraform.zip -d /usr/local/bin
          - deploy:
              name: Terraform INIT, PLAN and APPLY (or DESTROY)
              working_directory: ~/bia/terraform
              command: |
                terraform init -input=false
                terraform plan -input=false
                terraform apply -auto-approve

workflows:
  version: 2
  demo-deploy:
    jobs:
      - infrastructure
      
      
